# tasks file for cacti-plugin-percona
---
- name: install | dependencies
  apt:
    name: "{{ cacti_plugin_percona_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  notify: import templates
  tags:
    - cacti-plugin-percona-install-dependencies

- name: install | additional
  apt:
    name: "{{ cacti_plugin_percona_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - cacti-plugin-percona-install-additional
