# tasks file for cacti-plugin-percona
---
- name: install dependencies
  apt:
    name: "{{ cacti_plugin_percona_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-install
    - cacti-plugin-percona-install-dependencies

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ cacti_plugin_percona_downloads_path }}"
    - "{{ cacti_plugin_percona_builds_path }}"
    - "{{ cacti_plugin_percona_config_path }}"
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-directories
    - cacti-plugin-percona-directories-create

- name: download
  get_url:
    url: "https://downloads.percona.com/downloads/percona-monitoring-plugins/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}/source/tarball/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}.tar.gz"
    dest: "{{ cacti_plugin_percona_downloads_path }}/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}.tar.gz"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-downloads

- name: unarchive
  unarchive:
    src: "{{ cacti_plugin_percona_downloads_path }}/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}.tar.gz"
    dest: "{{ cacti_plugin_percona_builds_path }}"
    owner: root
    group: root
    creates: "{{ cacti_plugin_percona_builds_path }}/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}"
    copy: false
  register: _unarchive
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-unpack

- name: patch pmp-cacti-template
  lineinfile:
    path: "{{ cacti_plugin_percona_builds_path }}/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}/cacti/bin/pmp-cacti-template"
    regexp: '^our\ \$SVN_REV\ \=\ .*\;$'
    line: 'our $SVN_REV = 42;'
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-templates
    - cacti-plugin-percona-templates-patch
    - cacti-plugin-percona-templates-patch-pmp-cacti-template

- name: patch make.sh
  lineinfile:
    path: "{{ cacti_plugin_percona_builds_path }}/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}/make.sh"
    line: 'exit;'
    insertbefore: '^\#\ Generate\ Zabbix'
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-templates
    - cacti-plugin-percona-templates-patch
    - cacti-plugin-percona-templates-patch-make-sh

- name: make templates
  command: >
    ./make.sh
  args:
    chdir: "{{ cacti_plugin_percona_builds_path }}/percona-monitoring-plugins-{{ cacti_plugin_percona_version }}"
    creates: "{{ cacti_plugin_percona_release_path }}/templates"
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-templates
    - cacti-plugin-percona-templates-make

- name: import templates
  shell: >
    true \
    && test -f {{ cacti_plugin_percona_import_template_php_path }} \
    && find {{ cacti_plugin_percona_release_path }}/templates \
      -name '*.xml' \
      -print0 | \
      xargs -0 --no-run-if-empty -L1 -i'{}' \
      php {{ cacti_plugin_percona_import_template_php_path }} --filename='{}' {{ cacti_plugin_percona_import_template_php_options | join(' ') }}
  args:
    warn: false
  when: _unarchive is changed
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-templates
    - cacti-plugin-percona-templates-import

- name: install scripts
  shell: >
    true \
    && test -d {{ cacti_plugin_percona_release_path }}/scripts/ \
    && test -d {{ cacti_plugin_percona_scripts_path }}/ \
    && rsync \
      -ai --checksum --delete \
      --chown=root:root \
      {{ cacti_plugin_percona_release_path }}/scripts/ss_* \
      {{ cacti_plugin_percona_scripts_path }}/
  args:
    warn: false
  register: _scripts_copy
  changed_when: _scripts_copy.stdout_lines | length > 0
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-scripts
    - cacti-plugin-percona-scripts-install

- name: update configuration files
  template:
    src: "{{ item.lstrip('/') }}.j2"
    dest: "{{ item }}"
    owner: "{{ cacti_plugin_percona_ss_get_x_php_cnf_user }}"
    group: "{{ cacti_plugin_percona_ss_get_x_php_cnf_group }}"
    mode: "{{ cacti_plugin_percona_ss_get_x_php_cnf_mode }}"
  with_items:
    - "{{ cacti_plugin_percona_ss_get_by_ssh_php_cnf_file }}"
    - "{{ cacti_plugin_percona_ss_get_mysql_stats_php_cnf_file }}"
  tags:
    - configuration
    - cacti-plugin-percona
    - cacti-plugin-percona-scripts
    - cacti-plugin-percona-scripts-configure
