# tasks file for cacti-plugin-percona
---
- name: repository | add public key
  apt_key:
    id: CD2EFD2A
    url: http://www.percona.com/downloads/RPM-GPG-KEY-percona
    state: present
  tags:
    - cacti-plugin-percona-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: cacti_plugin_percona_repositories
  tags:
    - cacti-plugin-percona-repository-add

- name: repository | apt-pin packages
  copy:
    src: etc/apt/preferences.d/00percona.pref
    dest: /etc/apt/preferences.d/00percona.pref
    owner: root
    group: root
    mode: 0644
  tags:
    - cacti-plugin-percona-repository-apt-pin
